[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "assets_yaml_dsl_components"
defs_module = "assets_yaml_dsl_components.defs"

[tool.dagster]
module_name = "assets_yaml_dsl_components.definitions"
code_location_name = "assets_yaml_dsl_components"

# [project]
# name = "asset_yaml_dsl_components"
# 
# [project.entry-points]
# "dagster.components" = { asset_yaml_dsl_components = "asset_yaml_dsl_components.lib"}