sources:
  - name: jaffle_shop
    database: master_jaffle_shop
    schema: main
    tables:
      - name: raw_customers
        columns:
          - name: id 
            tests:
              - unique
              - not_null
