version: "3.7"

services:
  test-postgres-db-docker:
    image: postgres:11
    container_name: test-postgres-db-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - postgres

  s3:
    container_name: s3
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    name: postgres
